print('Cálculo da média, informe 4 notas')
nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))
nota3 = float(input('Digite a terceira nota: '))
nota4 = float(input('Digite a quarta nota: '))
print('A média das 4 notas é:', (nota1 + nota2 + nota3 + nota4)/4)
